---
galaxy_info:
  author: Francis Kayiwa
  description: user role
  company: docnow

  license: BSD

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 18.04

dependencies: []
